# Generated by Django 5.2.8 on 2026-07-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialsafety_1", "0003_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="contact",
        ),
    ]
