# Generated by Django 5.2.8 on 2026-07-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsafety_1", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="priority",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
