# Generated by Django 5.2.8 on 2026-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsafety_1", "0007_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
            ],
        ),
    ]
