# Generated by Django 5.2.8 on 2026-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsafety_1", "0009_remove_sos_user_name_sos_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="priority",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
