# Generated by Django 5.2.8 on 2026-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsafety_1", "0010_alter_contact_priority_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
